[package]
name = "actix_web_demo"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4"
mysql = "24.0"
redis = "0.25"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1", features = ["full"] } # 异步支持